// <auto-generated />
namespace ApplicationMyRoots.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class utp3331 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(utp3331));
        
        string IMigrationMetadata.Id
        {
            get { return "201711101939378_utp3331"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
