// <auto-generated />
namespace ApplicationMyRoots.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class otherpartners : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(otherpartners));
        
        string IMigrationMetadata.Id
        {
            get { return "201712041158485_otherpartners"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
